"""
PDF report generation

Copyright (c) 2025 Mattias Nyqvist
Licensed under the MIT License
"""

from reportlab.lib import colors
from reportlab.lib.pagesizes import letter, A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.platypus import SimpleDocTemplate, Table, TableStyle, Paragraph, Spacer, PageBreak
from reportlab.platypus import Image as RLImage
from reportlab.lib.enums import TA_CENTER, TA_LEFT, TA_JUSTIFY
from datetime import datetime
from typing import Dict
import io


def get_risk_color(risk_level: str) -> colors.Color:
    """Get color for risk level."""
    risk_colors = {
        'CRITICAL': colors.HexColor('#dc2626'),
        'HIGH': colors.HexColor('#ea580c'),
        'MEDIUM': colors.HexColor('#f59e0b'),
        'LOW': colors.HexColor('#059669'),
        'MINIMAL': colors.HexColor('#0891b2')
    }
    return risk_colors.get(risk_level, colors.grey)


def generate_pdf_report(analysis: Dict, filename: str) -> bytes:
    """
    Generate professional PDF report.
    
    Args:
        analysis: Analysis results dictionary
        filename: Contract filename
        
    Returns:
        PDF file as bytes
    """
    # Create PDF in memory
    buffer = io.BytesIO()
    
    # Create document
    doc = SimpleDocTemplate(
        buffer,
        pagesize=letter,
        rightMargin=72,
        leftMargin=72,
        topMargin=72,
        bottomMargin=18,
    )
    
    # Container for PDF elements
    elements = []
    
    # Styles
    styles = getSampleStyleSheet()
    
    # Custom styles
    title_style = ParagraphStyle(
        'CustomTitle',
        parent=styles['Heading1'],
        fontSize=24,
        textColor=colors.HexColor('#1f2937'),
        spaceAfter=30,
        alignment=TA_CENTER
    )
    
    heading_style = ParagraphStyle(
        'CustomHeading',
        parent=styles['Heading2'],
        fontSize=16,
        textColor=colors.HexColor('#1f2937'),
        spaceAfter=12,
        spaceBefore=12
    )
    
    body_style = ParagraphStyle(
        'CustomBody',
        parent=styles['BodyText'],
        fontSize=11,
        textColor=colors.HexColor('#374151'),
        spaceAfter=12,
        alignment=TA_JUSTIFY
    )
    
    # Title
    elements.append(Paragraph("CONTRACT RISK ANALYSIS REPORT", title_style))
    elements.append(Spacer(1, 12))
    
    # Metadata table
    metadata = [
        ['Contract:', filename],
        ['Analysis Date:', datetime.now().strftime('%Y-%m-%d %H:%M')],
        ['Generated By:', 'Contract Analyzer v1.0.0']
    ]
    
    metadata_table = Table(metadata, colWidths=[2*inch, 4*inch])
    metadata_table.setStyle(TableStyle([
        ('FONTNAME', (0, 0), (-1, -1), 'Helvetica'),
        ('FONTSIZE', (0, 0), (-1, -1), 10),
        ('TEXTCOLOR', (0, 0), (0, -1), colors.HexColor('#6b7280')),
        ('TEXTCOLOR', (1, 0), (1, -1), colors.HexColor('#1f2937')),
        ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 8),
    ]))
    
    elements.append(metadata_table)
    elements.append(Spacer(1, 20))
    
    # Overall Risk Badge
    overall_risk = analysis.get('overall_risk', 'UNKNOWN')
    risk_color = get_risk_color(overall_risk)
    
    risk_data = [[f'OVERALL RISK: {overall_risk}']]
    risk_table = Table(risk_data, colWidths=[6*inch])
    risk_table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, -1), risk_color),
        ('TEXTCOLOR', (0, 0), (-1, -1), colors.white),
        ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
        ('FONTNAME', (0, 0), (-1, -1), 'Helvetica-Bold'),
        ('FONTSIZE', (0, 0), (-1, -1), 16),
        ('TOPPADDING', (0, 0), (-1, -1), 12),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 12),
    ]))
    
    elements.append(risk_table)
    elements.append(Spacer(1, 20))
    
    # Key Metrics
    metrics_data = [
        ['Risks Identified', 'Red Flags', 'Missing Clauses', 'Recommendations'],
        [
            str(len(analysis.get('risks', []))),
            str(len(analysis.get('red_flags', []))),
            str(len(analysis.get('missing_clauses', []))),
            str(len(analysis.get('recommendations', [])))
        ]
    ]
    
    metrics_table = Table(metrics_data, colWidths=[1.5*inch]*4)
    metrics_table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#f3f4f6')),
        ('TEXTCOLOR', (0, 0), (-1, 0), colors.HexColor('#1f2937')),
        ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
        ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
        ('FONTSIZE', (0, 0), (-1, 0), 10),
        ('FONTNAME', (0, 1), (-1, 1), 'Helvetica-Bold'),
        ('FONTSIZE', (0, 1), (-1, 1), 18),
        ('TEXTCOLOR', (0, 1), (-1, 1), colors.HexColor('#3b82f6')),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 12),
        ('TOPPADDING', (0, 0), (-1, -1), 12),
        ('GRID', (0, 0), (-1, -1), 1, colors.HexColor('#e5e7eb'))
    ]))
    
    elements.append(metrics_table)
    elements.append(Spacer(1, 30))
    
    # Executive Summary
    elements.append(Paragraph("Executive Summary", heading_style))
    summary = analysis.get('summary', 'No summary available')
    elements.append(Paragraph(summary, body_style))
    elements.append(Spacer(1, 20))
    
    # Recommendations
    recommendations = analysis.get('recommendations', [])
    if recommendations:
        elements.append(Paragraph("Recommendations", heading_style))
        for i, rec in enumerate(recommendations, 1):
            rec_text = f"{i}. {rec}"
            elements.append(Paragraph(rec_text, body_style))
        elements.append(Spacer(1, 20))
    
    # Page break before detailed sections
    elements.append(PageBreak())
    
    # Risks
    risks = analysis.get('risks', [])
    if risks:
        elements.append(Paragraph("Detailed Risk Assessment", heading_style))
        elements.append(Spacer(1, 12))
        
        for risk in risks[:10]:  # Limit to 10 for PDF
            risk_level = risk.get('level', 'MEDIUM')
            risk_text = risk.get('text', 'Unknown risk')
            
            # Risk level badge
            risk_badge = Table([[risk_level]], colWidths=[1.5*inch])
            risk_badge.setStyle(TableStyle([
                ('BACKGROUND', (0, 0), (-1, -1), get_risk_color(risk_level)),
                ('TEXTCOLOR', (0, 0), (-1, -1), colors.white),
                ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
                ('FONTNAME', (0, 0), (-1, -1), 'Helvetica-Bold'),
                ('FONTSIZE', (0, 0), (-1, -1), 10),
                ('TOPPADDING', (0, 0), (-1, -1), 4),
                ('BOTTOMPADDING', (0, 0), (-1, -1), 4),
            ]))
            
            elements.append(risk_badge)
            elements.append(Spacer(1, 6))
            elements.append(Paragraph(risk_text, body_style))
            elements.append(Spacer(1, 12))
    
    # Red Flags
    red_flags = analysis.get('red_flags', [])
    if red_flags:
        elements.append(Paragraph("Red Flags", heading_style))
        for flag in red_flags:
            flag_text = f"⚠ {flag}"
            elements.append(Paragraph(flag_text, body_style))
        elements.append(Spacer(1, 20))
    
    # Missing Clauses
    missing = analysis.get('missing_clauses', [])
    if missing:
        elements.append(Paragraph("Missing Clauses", heading_style))
        for clause in missing:
            elements.append(Paragraph(f"• {clause}", body_style))
        elements.append(Spacer(1, 20))
    
    # Build PDF
    doc.build(elements)
    
    # Get PDF bytes
    pdf_bytes = buffer.getvalue()
    buffer.close()
    
    return pdf_bytes